package claude

// Claude Code hook_event_name values for config keys and stdin payloads.
const (
	EventSessionStart        = "SessionStart"
	EventSetup               = "Setup"
	EventSessionEnd          = "SessionEnd"
	EventUserPromptSubmit    = "UserPromptSubmit"
	EventUserPromptExpansion = "UserPromptExpansion"
	EventPreToolUse          = "PreToolUse"
	EventPostToolUse         = "PostToolUse"
	EventPostToolUseFailure  = "PostToolUseFailure"
	EventPostToolBatch       = "PostToolBatch"
	EventPermissionRequest   = "PermissionRequest"
	EventPermissionDenied    = "PermissionDenied"
	EventSubagentStart       = "SubagentStart"
	EventSubagentStop        = "SubagentStop"
	EventTaskCreated         = "TaskCreated"
	EventTaskCompleted       = "TaskCompleted"
	EventStop                = "Stop"
	EventStopFailure         = "StopFailure"
	EventTeammateIdle        = "TeammateIdle"
	EventNotification        = "Notification"
	EventMessageDisplay      = "MessageDisplay"
	EventInstructionsLoaded  = "InstructionsLoaded"
	EventConfigChange        = "ConfigChange"
	EventCwdChanged          = "CwdChanged"
	EventFileChanged         = "FileChanged"
	EventWorktreeCreate      = "WorktreeCreate"
	EventWorktreeRemove      = "WorktreeRemove"
	EventPreCompact          = "PreCompact"
	EventPostCompact         = "PostCompact"
	EventElicitation         = "Elicitation"
	EventElicitationResult   = "ElicitationResult"
)
