package event

// Claude Code hook_event_name values for config keys and stdin payloads.
const (
	SessionStart        = "SessionStart"
	Setup               = "Setup"
	SessionEnd          = "SessionEnd"
	UserPromptSubmit    = "UserPromptSubmit"
	UserPromptExpansion = "UserPromptExpansion"
	PreToolUse          = "PreToolUse"
	PostToolUse         = "PostToolUse"
	PostToolUseFailure  = "PostToolUseFailure"
	PostToolBatch       = "PostToolBatch"
	PermissionRequest   = "PermissionRequest"
	PermissionDenied    = "PermissionDenied"
	SubagentStart       = "SubagentStart"
	SubagentStop        = "SubagentStop"
	TaskCreated         = "TaskCreated"
	TaskCompleted       = "TaskCompleted"
	Stop                = "Stop"
	StopFailure         = "StopFailure"
	TeammateIdle        = "TeammateIdle"
	Notification        = "Notification"
	MessageDisplay      = "MessageDisplay"
	InstructionsLoaded  = "InstructionsLoaded"
	ConfigChange        = "ConfigChange"
	CwdChanged          = "CwdChanged"
	FileChanged         = "FileChanged"
	WorktreeCreate      = "WorktreeCreate"
	WorktreeRemove      = "WorktreeRemove"
	PreCompact          = "PreCompact"
	PostCompact         = "PostCompact"
	Elicitation         = "Elicitation"
	ElicitationResult   = "ElicitationResult"
)
