package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestMeasure_exportedCoverage(t *testing.T) {
	root := t.TempDir()
	pkg := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkg, 0o755); err != nil {
		t.Fatal(err)
	}

	src := `package pkg

// Documented is exported and documented.
func Documented() {}

func undocumented() {}

// ExportedType is documented.
type ExportedType struct {
	Field string
}

const (
	// ExportedConst is documented.
	ExportedConst = 1
)

var UndocumentedVar = 2
`
	if err := os.WriteFile(filepath.Join(pkg, "doc.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkg, "doc_test.go"), []byte("package pkg\nfunc TestX(t *testing.T) {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	report, err := measure(root)
	if err != nil {
		t.Fatal(err)
	}
	// Documented, ExportedType, ExportedConst documented; UndocumentedVar missing.
	// Field and undocumented() are not counted.
	if report.Total != 4 {
		t.Fatalf("total=%d want 4; missing=%v", report.Total, report.Missing)
	}
	if report.Documented != 3 {
		t.Fatalf("documented=%d want 3; missing=%v", report.Documented, report.Missing)
	}
	if len(report.Missing) != 1 || report.Missing[0] != "pkg/doc.go: var UndocumentedVar" {
		t.Fatalf("missing=%v", report.Missing)
	}
	wantPct := 75.0
	if report.Percent != wantPct {
		t.Fatalf("percent=%v want %v", report.Percent, wantPct)
	}
}

func TestMeasure_skipsGeneratedAndTestdata(t *testing.T) {
	root := t.TempDir()
	genDir := filepath.Join(root, "gen")
	testData := filepath.Join(root, "testdata")
	for _, dir := range []string{genDir, testData} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	generated := `// Code generated by hand. DO NOT EDIT.
package gen

func Undocumented() {}
`
	if err := os.WriteFile(filepath.Join(genDir, "gen.go"), []byte(generated), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(testData, "x.go"), []byte("package testdata\nfunc Undocumented() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	ok := `package gen

// Ok is documented.
func Ok() {}
`
	if err := os.WriteFile(filepath.Join(genDir, "ok.go"), []byte(ok), 0o644); err != nil {
		t.Fatal(err)
	}

	report, err := measure(root)
	if err != nil {
		t.Fatal(err)
	}
	if report.Total != 1 || report.Documented != 1 || len(report.Missing) != 0 {
		t.Fatalf("report=%+v", report)
	}
}
